-- MySQL Script generated by MySQL Workbench
-- Thu Sep 16 19:00:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocPizza
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocPizza` ;

-- -----------------------------------------------------
-- Schema ocPizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocPizza` DEFAULT CHARACTER SET utf8 ;
USE `ocPizza` ;

-- -----------------------------------------------------
-- Table `ocPizza`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`commande` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_commande` VARCHAR(20) NOT NULL,
  `date` DATETIME(20) NOT NULL,
  `quantite` INT NOT NULL,
  `prix_total` DECIMAL(6) NOT NULL,
  `etat` ENUM('en_cours', 'recu', 'livre', 'annule') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Commande_utilisateur_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_utilisateur`
    FOREIGN KEY (`user_id`)
    REFERENCES `ocPizza`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`adresse` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`adresse` (
  `id` INT NULL AUTO_INCREMENT,
  `numero_voie` INT NOT NULL,
  `voie` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NULL,
  `code_postale` INT NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Adresse_Commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_Adresse_Commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `ocPizza`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`user` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identifiant` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(200) NOT NULL,
  `role` ENUM('client', 'employe', 'responsable', 'livreur') NOT NULL DEFAULT '<<ENUM>> Role(Client, Responsable, Employe, Livreur)',
  `numero_telephone` VARCHAR(15) NULL,
  `adresse_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_adresse1_idx` (`adresse_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `ocPizza`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`pizzas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` LONGBLOB NULL,
  `prix_unitaireHT` DECIMAL(6) NOT NULL,
  `tauxTVA` DECIMAL(6) NOT NULL,
  `taille` ENUM('petite', 'moyenne', 'grande') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`pizzas_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`pizzas_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`pizzas_has_ingredients` (
  `pizzas_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`pizzas_id`, `ingredients_id`),
  INDEX `fk_pizzas_has_ingredients_ingredients1_idx` (`ingredients_id` ASC) VISIBLE,
  INDEX `fk_pizzas_has_ingredients_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_has_ingredients_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `ocPizza`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzas_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `ocPizza`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`variente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`variente` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`variente` (
  `idVariente` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idVariente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`pizza` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`pizza` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` LONGBLOB NOT NULL,
  `prix_unitaire` DECIMAL NOT NULL,
  `taux_TVA` DECIMAL NOT NULL,
  `variente_idVariente` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_article_variente1_idx` (`variente_idVariente` ASC) VISIBLE,
  CONSTRAINT `fk_article_variente1`
    FOREIGN KEY (`variente_idVariente`)
    REFERENCES `ocPizza`.`variente` (`idVariente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`categorie` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`categorie` (
  `idCategorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`commande_has_variente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`commande_has_variente` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`commande_has_variente` (
  `commande_id` INT NOT NULL,
  `variente_idVariente` INT NOT NULL,
  PRIMARY KEY (`commande_id`, `variente_idVariente`),
  INDEX `fk_commande_has_variente_variente1_idx` (`variente_idVariente` ASC) VISIBLE,
  INDEX `fk_commande_has_variente_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_variente_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `ocPizza`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_has_variente_variente1`
    FOREIGN KEY (`variente_idVariente`)
    REFERENCES `ocPizza`.`variente` (`idVariente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`stock` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`stock` (
  `idstock` INT NOT NULL AUTO_INCREMENT,
  `articles_id` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`idstock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`aide_memoire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`aide_memoire` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`aide_memoire` (
  `idaide_memoire` INT NOT NULL AUTO_INCREMENT,
  `nom_pizza` VARCHAR(45) NOT NULL,
  `pizza_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`idaide_memoire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`commande_has_pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`commande_has_pizzas` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`commande_has_pizzas` (
  `commande_id` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  PRIMARY KEY (`commande_id`, `pizzas_id`),
  INDEX `fk_commande_has_pizzas_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  INDEX `fk_commande_has_pizzas_commande1_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_pizzas_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `ocPizza`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_has_pizzas_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `ocPizza`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocPizza`.`aide-memoire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocPizza`.`aide-memoire` ;

CREATE TABLE IF NOT EXISTS `ocPizza`.`aide-memoire` (
  `Id` INT NOT NULL,
  `recette` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `duree_de_preparation` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  PRIMARY KEY (`Id`, `pizzas_id`),
  INDEX `fk_aide-memoire_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  CONSTRAINT `fk_aide-memoire_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `ocPizza`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
